### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by Sinono3** [Sinono3/souvlaki#32]
`unwrap` is used a lot throughout the code at this moment. And the platform errors don't implement `std::error::Error`. Both seem to be easy fixes.

**Comment by Sinono3** [comment]
Mainly the zbus backend needs better error handling now, this will come with v0.8

**Comment by hasezoey** [comment]
I have noticed that the following place is still using unwraps, which could be a problem when `panic = abort` is used:
https://github.com/Sinono3/souvlaki/blob/e6ff34b30bec98829b7c569e7974c78d9ac8253d/src/platform/mpris/zbus.rs#L97-L98

<details>
<summary>The Error trace from our side (0.7.3)</summary>

This Error trace is what got me to investigate it, and it should still be somewhat relevant in 0.8.0 regarding `panic = abort`:

```txt
[2024-12-09T22:59:43.712+01:00 ERROR termusic_server::logger]: Panic occured:
panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:100:22:
called `Result::unwrap()` on an `Err` value: NameTaken
disabled backtrace
thread '<unnamed>' panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:100:22:
called `Result::unwrap()` on an `Err` value: NameTaken
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2024-12-09T22:59:43.811+01:00 ERROR termusic_server::logger]: Panic occured:
panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:139:29:
called `Result::unwrap()` on an `Err` value: SendError { .. }
disabled backtrace
thread 'main player loop' panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:139:29:
called `Result::unwrap()` on an `Err` value: SendError { .. }
[2024-12-09T22:59:43.811+01:00 ERROR termusic_server::logger]: Panic occured:
panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:112:53:
called `Result::unwrap()` on an `Err` value: SendError { .. }
disabled backtrace
thread 'main player loop' panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:112:53:
called `Result::unwrap()` on an `Err` value: SendError { .. }
```
[Original Issue](https://github.com/tramhao/termusic/issues/398)

</details>
